// A small curated starting directory, not an exhaustive list. Every field accepts custom entries.
export const universities: {
  province: string;
  name: string;
  type: string;
  faculties: string[];
}[] = [
  {
    province: "DKI Jakarta",
    name: "Universitas Indonesia",
    type: "Universitas Negeri",
    faculties: [
      "Ilmu Komputer",
      "Ekonomi dan Bisnis",
      "Teknik",
      "Hukum",
      "Ilmu Pengetahuan Budaya",
      "Kedokteran",
    ],
  },
  {
    province: "DI Yogyakarta",
    name: "Universitas Gadjah Mada",
    type: "Universitas Negeri",
    faculties: [
      "Teknik",
      "Ekonomika dan Bisnis",
      "Ilmu Sosial dan Ilmu Politik",
      "Kedokteran",
      "Pertanian",
    ],
  },
  {
    province: "Jawa Barat",
    name: "Institut Teknologi Bandung",
    type: "Institut Negeri",
    faculties: [
      "Teknik Elektro dan Informatika",
      "Teknologi Industri",
      "Sains",
      "Seni Rupa dan Desain",
    ],
  },
  {
    province: "Jawa Tengah",
    name: "Universitas Diponegoro",
    type: "Universitas Negeri",
    faculties: [
      "Teknik",
      "Ekonomika dan Bisnis",
      "Sains dan Matematika",
      "Hukum",
    ],
  },
  {
    province: "Jawa Tengah",
    name: "Universitas Jenderal Soedirman",
    type: "Universitas Negeri",
    faculties: [
      "Teknik",
      "Ekonomi dan Bisnis",
      "Ilmu Sosial dan Ilmu Politik",
      "Pertanian",
    ],
  },
  {
    province: "Jawa Tengah",
    name: "STIKOM Yos Sudarso",
    type: "Sekolah Tinggi Swasta",
    faculties: ["Komputer dan Informatika"],
  },
  {
    province: "Jawa Timur",
    name: "Institut Teknologi Sepuluh Nopember",
    type: "Institut Negeri",
    faculties: [
      "Teknologi Elektro dan Informatika Cerdas",
      "Teknologi Industri dan Rekayasa Sistem",
      "Desain Kreatif dan Bisnis Digital",
    ],
  },
  {
    province: "Jawa Timur",
    name: "Universitas Airlangga",
    type: "Universitas Negeri",
    faculties: [
      "Ekonomi dan Bisnis",
      "Sains dan Teknologi",
      "Hukum",
      "Kedokteran",
    ],
  },
  {
    province: "Bali",
    name: "Universitas Udayana",
    type: "Universitas Negeri",
    faculties: ["Teknik", "Ekonomi dan Bisnis", "Pariwisata", "Kedokteran"],
  },
  {
    province: "Sulawesi Selatan",
    name: "Universitas Hasanuddin",
    type: "Universitas Negeri",
    faculties: ["Teknik", "Ekonomi dan Bisnis", "Ilmu Sosial dan Ilmu Politik"],
  },
  {
    province: "Sumatera Utara",
    name: "Universitas Sumatera Utara",
    type: "Universitas Negeri",
    faculties: [
      "Ilmu Komputer dan Teknologi Informasi",
      "Teknik",
      "Ekonomi dan Bisnis",
    ],
  },
  {
    province: "Jawa Barat",
    name: "Universitas Padjadjaran",
    type: "Universitas Negeri",
    faculties: ["Ilmu Komunikasi", "Ekonomi dan Bisnis", "Teknik Geologi"],
  },
];
export const provinces = [
  "Aceh",
  "Sumatera Utara",
  "Sumatera Barat",
  "Riau",
  "Kepulauan Riau",
  "Jambi",
  "Bengkulu",
  "Sumatera Selatan",
  "Kepulauan Bangka Belitung",
  "Lampung",
  "DKI Jakarta",
  "Banten",
  "Jawa Barat",
  "Jawa Tengah",
  "DI Yogyakarta",
  "Jawa Timur",
  "Bali",
  "Nusa Tenggara Barat",
  "Nusa Tenggara Timur",
  "Kalimantan Barat",
  "Kalimantan Tengah",
  "Kalimantan Selatan",
  "Kalimantan Timur",
  "Kalimantan Utara",
  "Sulawesi Utara",
  "Gorontalo",
  "Sulawesi Tengah",
  "Sulawesi Barat",
  "Sulawesi Selatan",
  "Sulawesi Tenggara",
  "Maluku",
  "Maluku Utara",
  "Papua",
  "Papua Barat",
  "Papua Selatan",
  "Papua Tengah",
  "Papua Pegunungan",
  "Papua Barat Daya",
];
